file_format: "1"
id: bleeckeys
name: Bleeckeys
type: shield
url: https://github.com/Bleeck/zmk-config
requires: [pro_micro]
exposes: [i2c_glidepoint]
features:
  - keys
  - display
  - studio
siblings:
  - bleeckeys_left
  - bleeckeys_right